### ISSUE TITLE
Add extra timeout for Tasks

### ISSUE THREAD

**Issue by odarriba** [acutario/ravenx#20]
On Tasks (which is the process type currently used on Ravenx) the default timeout is 5 seconds, which couldn't be enough if we are dealing with external providers.

At least, we should increase the timeout up to ¿10 seconds?

Also, it would be interesting to supervise these tasks in case they die, but this should be defined as it could be an overdesign.

**Comment by rsierra** [comment]
What about do this configurable in the strategy? Timeout and retries, 10 seconds and 0 retries by default?

**Comment by odarriba** [comment]
Awesome idea. Maybe this could be added to the next major version, alongside with other improvements in the area of multitasking (pooling tasks and monitoring them, just a quick idea).

**Comment by odarriba** [comment]
As we need to do a release, moving this to the next one

**Comment by odarriba** [comment]
Closing this at the moment
