### ISSUE TITLE
Limit the amount of tasks that can be handled simultaneously

### ISSUE THREAD

**Issue by odarriba** [acutario/ravenx#22]
The idea is to avoid using `Tasks` to execute the dispatch works and try to use something more robust like `:poolboy` with `GenStage`

**Comment by vortizhe** [comment]
:heart: :blue_heart: :green_heart: :yellow_heart: :purple_heart:

**Comment by odarriba** [comment]
I've tested the amount of tasks needed to get inestability inside Erlang VM and it really depends on the strategy used.

In general, as the great ampunt of time used is waiting for external responses (and not doing CPU-intensive work), I don't have a clear if this deserves the amount of complexity it will add to code base.

So closing for now.
