### ISSUE TITLE
Pusher Integration

### ISSUE THREAD

**Issue by behind-design** [acutario/ravenx#31]
Hi there @odarriba!

First of all thank you for you library I discovered it through your post on Medium and I really liked the idea and I wanted to give it a try with a small part of a side project.

With good spirit I created a new Strategy to integrate `Pusher` into the mix.
You can take a look here [RavenxPusher](https://github.com/behind-design/ravenx-pusher).
And so I was hoping that we can add said strategy to your README in order to reflect the implementation in case anyone needs it.

Again thank you for the amazing work and keep 'em coming!

**Comment by odarriba** [comment]
Hi!

So nice to see the first community-driven strategy for Ravenx!
Of course we can add your library to the README, so anyone watching for a Pusher integration can found it.

Just to mention that we are going to start developing next major release (look at #30 and #28 ), so future updates will be required. But don't worry! we will let you know when that happens :)

**Comment by odarriba** [comment]
I just added it to the README.
Thanks again for this amazing work!

**Comment by behind-design** [comment]
@odarriba Perfect I'll be in the look out!
